#pragma once

#define SECRET_WIFI_SSID "YOUR_WIFI_SSID"
#define SECRET_WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#define SECRET_THINGSPEAK_CHANNEL_ID "YOUR_CHANNEL_ID"
#define SECRET_THINGSPEAK_READ_API_KEY "YOUR_READ_API_KEY"
